name: learn-githubactions
on: [push]
jobs:
 firstJob:
  runs-on: ubunru-latest
  steps:
   - uses: actions/checkout@v3
   - uses: actions/setup-node@v3
     with:
      node-version: '14'
   - uses: sfdx-actions/setup-sfdx@v1
   
   - name: sfdx version check
     run: sfdx -v
   - name: node version check
     run: node -v
	    
   - name: Create a file to store access key
     run: touch access_build.key
     shell: bash 
	 
   - name: add salesforce key to the file
     run: echo 'force://PlatformCLI::5Aep861g78ZB7.52BdYasUbDan_s7oBOvrelOrTzqjp2_k_mugQa9oKEAZbMBXEHAjY.Szu1jM_2R.lGTV08.KQ@vrp280-dev-ed.my.salesforce.com' > access_build.key 
     shell: bash 
   - name: Authorization on Salesforce Build org
     run: node_modules/sfdx-cli/bin/run force:auth:sfdxurl:store -f 'access_build.key' -a org.build	 
	 
	 
	 
	 
	 
	 
   #- name: Authorization on Salesforce Build org
    # run: sfdx force:auth:sfdxurl:store -f 'access_build.key' -a org.build
	# shell: bash 
	 
	 

	 
#- bash:    
 #             echo $SF_URL_build > access_build.key   
#   - run: npm install -g bats

     
